# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [2]:
np.random.rand(4,3)

array([[0.56408958, 0.08128464, 0.14465786],
       [0.67630993, 0.87610016, 0.25112844],
       [0.12570398, 0.32251291, 0.9725334 ],
       [0.4936494 , 0.37955277, 0.0916901 ]])

In [3]:
np.random.rand(3,3)

array([[0.25257842, 0.28560439, 0.33000116],
       [0.98964429, 0.42660778, 0.2051556 ],
       [0.61452119, 0.92219928, 0.19972581]])

In [4]:
np.random.rand(2,3)

array([[0.29167431, 0.20499917, 0.77548031],
       [0.52062524, 0.05547136, 0.46935275]])

This function allows you to randomly generate an array of numbers in matrix array format

## numpy.random.randint

In [5]:
np.random.randint(2, size=10)

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1])

In [6]:
np.random.randint(4, size=10)

array([2, 3, 2, 2, 0, 1, 2, 3, 3, 3])

In [7]:
np.random.randint(-2, size=10)

ValueError: low >= high

In [ ]:
np.random.randint(5, size=8)

in this funtion numpy.random.randint it prints out a random number between 0 and what ever number you enter, and prints it out in the size of the array you have entered aswel. if you enter a minus it will trough an error as showing.

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
np.random.randint(6, size=(3, 5))

In [ ]:
np.random.randint(6, size=(5, 5))

also in this funtion numpy.random.randint generates random numbers in the size of a matrix you wish to enter. 

## numpy.random.random_sample

In [ ]:
np.random.random_sample()

In [ ]:
np.random.random_sample()

In [ ]:
type(np.random.random_sample())

In [ ]:
np.random.random_sample((5))

In [ ]:
np.random.random_sample((3))

In [ ]:
np.random.random_sample((10))

this funtion numpy.random.random_sample generats a random number as a float. You can select the can also select the size of the array.

In [ ]:
5 * np.random.random_sample((3, 2)) -5

In [ ]:
5 * np.random.random_sample((3, 2)) 5

In [ ]:
5 * np.random.random_sample((3, 2)) -2

In [ ]:
5 * np.random.random_sample((3, 2)) -4

In [ ]:
5 * np.random.random_sample((3, 2)) -3

In [ ]:
5 * np.random.random_sample((3, 2)) -1

In [ ]:
3 * np.random.random_sample((3, 2)) -1

In [ ]:
2 * np.random.random_sample((3, 2)) -2

In [ ]:
1 * np.random.random_sample((3, 2)) -1

This funtion generates an matrix array in a float between the two munber you have selected at ether end of the funtion.

## numpy.random.bytes 

In [ ]:
np.random.bytes(10)

In [ ]:
np.random.bytes(9)

In [ ]:
np.random.bytes(5)

In [ ]:
np.random.bytes(1)

This funtion returns random size bytes.

## numpy.random.shuffle

In [ ]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(5)
np.random.shuffle(arr)
arr

This funtion generats the array and shuffles the number in the array. generated by the number entered.

In [ ]:
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(16).reshape((4, 4))
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(4).reshape((2, 2))
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(6).reshape((3, 2))
np.random.shuffle(arr)
arr

this funtion shuffles the array in a matrix array.

## nimpy.random.permutation

In [ ]:
np.random.permutation(10)

In [ ]:
np.random.permutation(5)

This funtion permutation shuffles the number in the array

In [ ]:
np.random.permutation([1,4,9,12,15])

In [ ]:
np.random.permutation([1,2,3,4,5,6])

This funtion of permutation shuffles the list of number you have entered into an array.

In [ ]:
arr = np.arange(9).reshape((3,3))
np.random.permutation(arr)

In [ ]:
arr = np.arange(16).reshape((4,4))
np.random.permutation(arr)

In [ ]:
arr = np.arange(4).reshape((2,2))
np.random.permutation(arr)

This funtion of premutation shuffles the number array into a matrix array.

## numpy.random.geometric

In [ ]:
z = np.random.geometric(p=0.35, size=1000)

In [ ]:
(z == 1).sum()/1000.

In [ ]:
z = np.random.geometric(p=0.35, size=1000)

In [ ]:
(z == 1).sum()/1000.

In [ ]:
z = np.random.geometric(p=0.35, size=1000)

In [ ]:
(z == 1).sum()/1000.

This funtion of geometric draws ten thousand values from the geometric distribution, with the probability of an indiviual success equal to .35: its an experiment with one or two outcomes, success or failure. 

## numpy.random.hypergeometric

In [12]:
s = np.random.hypergeometric(15,15,15,100000)

In [13]:
sum(s>=12)/10000. + sum(s<=3)/100000.

0.01663

This funtion of hypergeometric. is what are the chances of getting 12 of the same color pulled out 15 pretty unlikely out of 100000 of that happening.