# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [5]:
np.random.rand(4,3)

array([[0.59693637, 0.37018092, 0.58094636],
       [0.7710355 , 0.42736991, 0.95695496],
       [0.67679842, 0.21580277, 0.03681466],
       [0.88398653, 0.35384871, 0.90981316]])

In [4]:
np.random.rand(3,3)

array([[0.37395559, 0.72830416, 0.69090118],
       [0.4256065 , 0.8383499 , 0.10629013],
       [0.54396887, 0.06500012, 0.32724002]])

In [8]:
np.random.rand(2,3)

array([[0.68609587, 0.02857338, 0.42582676],
       [0.12863762, 0.80042862, 0.56268153]])

This function allows you to randomly generate an array of numbers in matrix array format