# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [2]:
np.random.rand(4,3)

array([[0.95196729, 0.82577571, 0.11756935],
       [0.86083415, 0.52583556, 0.21969384],
       [0.80296353, 0.73403171, 0.77616824],
       [0.77594523, 0.35921654, 0.53438608]])

In [3]:
np.random.rand(3,3)

array([[0.35171621, 0.63585856, 0.90513219],
       [0.35776897, 0.14919273, 0.98615292],
       [0.18886981, 0.13553513, 0.31971341]])

In [4]:
np.random.rand(2,3)

array([[0.01940059, 0.60869289, 0.30468226],
       [0.57083428, 0.49025724, 0.5897192 ]])

This function allows you to randomly generate an array of numbers in matrix array format

## numpy.random.randint

In [5]:
np.random.randint(2, size=10)

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [6]:
np.random.randint(4, size=10)

array([1, 3, 3, 1, 3, 2, 2, 3, 3, 1])

In [7]:
np.random.randint(-2, size=10)

ValueError: low >= high

In [ ]:
np.random.randint(5, size=8)

in this funtion numpy.random.randint it prints out a random number between 0 and what ever number you enter, and prints it out in the size of the array you have entered aswel. if you enter a minus it will trough an error as showing.

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
np.random.randint(6, size=(3, 5))

In [ ]:
np.random.randint(6, size=(5, 5))

also in this funtion numpy.random.randint generates random numbers in the size of a matrix you wish to enter. 

## numpy.random.random_sample

In [ ]:
np.random.random_sample()

In [ ]:
np.random.random_sample()

In [ ]:
type(np.random.random_sample())

In [ ]:
np.random.random_sample((5))

In [ ]:
np.random.random_sample((3))

In [ ]:
np.random.random_sample((10))

this funtion numpy.random.random_sample generats a random number as a float. You can select the can also select the size of the array.

In [ ]:
5 * np.random.random_sample((3, 2)) -5

In [ ]:
5 * np.random.random_sample((3, 2)) 5

In [ ]:
5 * np.random.random_sample((3, 2)) -2

In [ ]:
5 * np.random.random_sample((3, 2)) -4

In [ ]:
5 * np.random.random_sample((3, 2)) -3

In [ ]:
5 * np.random.random_sample((3, 2)) -1

In [ ]:
3 * np.random.random_sample((3, 2)) -1

In [ ]:
2 * np.random.random_sample((3, 2)) -2

In [ ]:
1 * np.random.random_sample((3, 2)) -1

This funtion generates an matrix array in a float between the two munber you have selected at ether end of the funtion.

## numpy.random.bytes 

In [ ]:
np.random.bytes(10)

In [ ]:
np.random.bytes(9)

In [ ]:
np.random.bytes(5)

In [ ]:
np.random.bytes(1)

This funtion returns random size bytes.

## numpy.random.shuffle

In [10]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([1, 5, 8, 2, 7, 4, 6, 3, 0, 9])

In [12]:
arr = np.arange(5)
np.random.shuffle(arr)
arr

array([3, 2, 4, 0, 1])

This funtion generats the array and shuffles the number in the array. generated by the number entered.

In [13]:
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
arr

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [16]:
arr = np.arange(16).reshape((4, 4))
np.random.shuffle(arr)
arr

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7]])

In [17]:
arr = np.arange(4).reshape((2, 2))
np.random.shuffle(arr)
arr

array([[2, 3],
       [0, 1]])

In [18]:
arr = np.arange(6).reshape((3, 2))
np.random.shuffle(arr)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

this funtion shuffles the array in a matrix array.