# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [2]:
np.random.rand(4,3)

array([[0.1055041 , 0.97663504, 0.43773201],
       [0.58904939, 0.60112714, 0.74584481],
       [0.77340937, 0.53863352, 0.03265967],
       [0.37607587, 0.74741784, 0.95568022]])

In [3]:
np.random.rand(3,3)

array([[0.74977202, 0.01135734, 0.00583484],
       [0.46410874, 0.75570271, 0.73263559],
       [0.67159329, 0.67084551, 0.86501894]])

In [4]:
np.random.rand(2,3)

array([[0.37754628, 0.0541481 , 0.34778568],
       [0.537073  , 0.36745737, 0.91340667]])

This function allows you to randomly generate an array of numbers in matrix array format

## numpy.random.randint

In [5]:
np.random.randint(2, size=10)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1])

In [6]:
np.random.randint(4, size=10)

array([3, 2, 2, 3, 1, 1, 2, 1, 2, 3])

In [7]:
np.random.randint(-2, size=10)

ValueError: low >= high

In [ ]:
np.random.randint(5, size=8)

in this funtion numpy.random.randint it prints out a random number between 0 and what ever number you enter, and prints it out in the size of the array you have entered aswel. if you enter a minus it will trough an error as showing.

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
np.random.randint(6, size=(3, 5))

In [ ]:
np.random.randint(6, size=(5, 5))

also in this funtion numpy.random.randint generates random numbers in the size of a matrix you wish to enter. 

## numpy.random.random_sample

In [ ]:
np.random.random_sample()

In [ ]:
np.random.random_sample()

In [ ]:
type(np.random.random_sample())

In [ ]:
np.random.random_sample((5))

In [ ]:
np.random.random_sample((3))

In [ ]:
np.random.random_sample((10))

this funtion numpy.random.random_sample generats a random number as a float. You can select the can also select the size of the array.

In [ ]:
5 * np.random.random_sample((3, 2)) -5

In [ ]:
5 * np.random.random_sample((3, 2)) 5

In [ ]:
5 * np.random.random_sample((3, 2)) -2

In [ ]:
5 * np.random.random_sample((3, 2)) -4

In [ ]:
5 * np.random.random_sample((3, 2)) -3

In [ ]:
5 * np.random.random_sample((3, 2)) -1

In [ ]:
3 * np.random.random_sample((3, 2)) -1

In [ ]:
2 * np.random.random_sample((3, 2)) -2

In [ ]:
1 * np.random.random_sample((3, 2)) -1

This funtion generates an matrix array in a float between the two munber you have selected at ether end of the funtion.

## numpy.random.bytes 

In [ ]:
np.random.bytes(10)

In [ ]:
np.random.bytes(9)

In [ ]:
np.random.bytes(5)

In [ ]:
np.random.bytes(1)

This funtion returns random size bytes.

## numpy.random.shuffle

In [ ]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(5)
np.random.shuffle(arr)
arr

This funtion generats the array and shuffles the number in the array. generated by the number entered.

In [ ]:
arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(16).reshape((4, 4))
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(4).reshape((2, 2))
np.random.shuffle(arr)
arr

In [ ]:
arr = np.arange(6).reshape((3, 2))
np.random.shuffle(arr)
arr

this funtion shuffles the array in a matrix array.

## nimpy.random.permutation

In [8]:
np.random.permutation(10)

array([9, 7, 0, 6, 8, 1, 2, 4, 5, 3])

In [9]:
np.random.permutation(5)

array([0, 1, 3, 4, 2])

This funtion permutation shuffles the number in the array

In [10]:
np.random.permutation([1,4,9,12,15])

array([ 9, 15,  1,  4, 12])

In [11]:
np.random.permutation([1,2,3,4,5,6])

array([4, 2, 3, 5, 1, 6])

This funtion of permutation shuffles the list of number you have entered into an array.

In [12]:
arr = np.arange(9).reshape((3,3))
np.random.permutation(arr)

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [13]:
arr = np.arange(16).reshape((4,4))
np.random.permutation(arr)

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [14]:
arr = np.arange(4).reshape((2,2))
np.random.permutation(arr)

array([[0, 1],
       [2, 3]])

This funtion of premutation shuffles the number array into a matrix array.