# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [2]:
np.random.rand(4,3)

array([[0.59472887, 0.66592359, 0.5554423 ],
       [0.52790043, 0.81832008, 0.42197073],
       [0.44421815, 0.43102331, 0.93444552],
       [0.94140151, 0.43095199, 0.49748022]])

In [3]:
np.random.rand(3,3)

array([[0.32562518, 0.58846321, 0.92638409],
       [0.15034642, 0.42035286, 0.66543508],
       [0.99003156, 0.69946615, 0.20934333]])

In [4]:
np.random.rand(2,3)

array([[0.48324661, 0.83727952, 0.79390833],
       [0.09792371, 0.98584623, 0.33140807]])

This function allows you to randomly generate an array of numbers in matrix array format

## numpy.random.randint

In [5]:
np.random.randint(2, size=10)

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1])

In [6]:
np.random.randint(4, size=10)

array([1, 1, 0, 0, 3, 1, 2, 3, 2, 1])

In [7]:
np.random.randint(-2, size=10)

ValueError: low >= high

In [ ]:
np.random.randint(5, size=8)

in this funtion numpy.random.randint it prints out a random number between 0 and what ever number you enter, and prints it out in the size of the array you have entered aswel. if you enter a minus it will trough an error as showing.

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
np.random.randint(6, size=(3, 5))

In [ ]:
np.random.randint(6, size=(5, 5))

also in this funtion numpy.random.randint generates random numbers in the size of a matrix you wish to enter. 

## numpy.random.random_sample

In [8]:
np.random.random_sample()

0.4830448775859202

In [9]:
np.random.random_sample()

0.13626840285995512

In [10]:
type(np.random.random_sample())

float

In [11]:
np.random.random_sample((5))

array([0.09332116, 0.5420089 , 0.13527108, 0.37668603, 0.24483753])

In [12]:
np.random.random_sample((3))

array([0.7187208 , 0.85859561, 0.06291839])

In [13]:
np.random.random_sample((10))

array([0.75778677, 0.68133497, 0.21112501, 0.83737128, 0.66725251,
       0.90704639, 0.13286966, 0.18706335, 0.54020804, 0.99229154])

this funtion numpy.random.random_sample generats a random number as a float. You can select the can also select the size of the array.

In [14]:
5 * np.random.random_sample((3, 2)) -5

array([[-3.28405153, -3.31721672],
       [-2.87575695, -1.536854  ],
       [-4.42372348, -3.88545378]])

In [15]:
5 * np.random.random_sample((3, 2)) 5

SyntaxError: invalid syntax (<ipython-input-15-bcc97899b645>, line 1)

In [16]:
5 * np.random.random_sample((3, 2)) -2

array([[ 2.43692349,  2.82634181],
       [ 0.95050864, -0.51305336],
       [ 1.17877632,  0.38569077]])

In [17]:
5 * np.random.random_sample((3, 2)) -4

array([[-2.41444154, -3.39300896],
       [-1.80035416, -3.98042951],
       [ 0.40874544, -0.96501714]])

In [18]:
5 * np.random.random_sample((3, 2)) -3

array([[-0.57058623, -0.78844194],
       [ 1.35820207,  0.71564261],
       [-0.33005856, -2.85740785]])

In [19]:
5 * np.random.random_sample((3, 2)) -1

array([[ 0.73462277,  1.07167773],
       [-0.58809734,  1.8382333 ],
       [ 3.85701604,  3.16791345]])

In [20]:
3 * np.random.random_sample((3, 2)) -1

array([[-0.88493076,  0.16645764],
       [ 0.32449271, -0.46136733],
       [-0.09738802, -0.73509824]])

In [21]:
2 * np.random.random_sample((3, 2)) -2

array([[-1.13773843, -0.37145552],
       [-0.11040581, -0.07342382],
       [-0.51355362, -0.3032672 ]])

In [22]:
1 * np.random.random_sample((3, 2)) -1

array([[-0.01996199, -0.85701522],
       [-0.25520702, -0.01635547],
       [-0.37951162, -0.01361276]])

This funtion generates an matrix array in a float between the two munber you have selected at ether end of the funtion.