# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [2]:
np.random.rand(4,3)

array([[0.61042182, 0.81637861, 0.92632817],
       [0.62517175, 0.8991319 , 0.79417989],
       [0.54805841, 0.50581268, 0.15566523],
       [0.78840216, 0.81686006, 0.28825961]])

In [3]:
np.random.rand(3,3)

array([[0.72095616, 0.66557542, 0.45640893],
       [0.33512382, 0.14050243, 0.08193666],
       [0.57058085, 0.64536064, 0.15453501]])

In [4]:
np.random.rand(2,3)

array([[0.17849052, 0.25151657, 0.1350727 ],
       [0.25111925, 0.12271315, 0.92660379]])

This function allows you to randomly generate an array of numbers in matrix array format

## numpy.random.randint

In [5]:
np.random.randint(2, size=10)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [6]:
np.random.randint(4, size=10)

array([0, 2, 2, 0, 1, 2, 2, 2, 1, 2])

In [7]:
np.random.randint(-2, size=10)

ValueError: low >= high

In [ ]:
np.random.randint(5, size=8)

in this funtion numpy.random.randint it prints out a random number between 0 and what ever number you enter, and prints it out in the size of the array you have entered aswel. if you enter a minus it will trough an error as showing.

In [ ]:
np.random.randint(5, size=(2, 4))

In [ ]:
np.random.randint(6, size=(3, 5))

In [ ]:
np.random.randint(6, size=(5, 5))

also in this funtion numpy.random.randint generates random numbers in the size of a matrix you wish to enter. 

## numpy.random.random_sample

In [8]:
np.random.random_sample()

0.4957761901144392

In [9]:
np.random.random_sample()

0.6921217517688347

In [10]:
type(np.random.random_sample())

float

In [11]:
np.random.random_sample((5))

array([0.99726006, 0.10581498, 0.83184482, 0.4652399 , 0.81969549])

In [12]:
np.random.random_sample((3))

array([0.11932368, 0.40576034, 0.96008695])

In [13]:
np.random.random_sample((10))

array([0.10010568, 0.75097868, 0.09323356, 0.83853808, 0.48582166,
       0.44815683, 0.37578708, 0.14473193, 0.33797767, 0.53272885])

this funtion numpy.random.random_sample generats a random number as a float. You can select the can also select the size of the array.