# The numpy.random package

NumPy is the fundamental package needed for scientific computing with Python. This package contains:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
basic linear algebra functions
basic Fourier transforms
sophisticated random number capabilities
tools for integrating Fortran code
tools for integrating C/C++ code

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy is a successor for two earlier scientific Python libraries: NumPy derives from the old Numeric code base and can be used as a replacement for Numeric. It also adds the features introduced by Numarray and can also be used to replace Numarray.


## Import 

In [1]:
import numpy as np

In the notebook you mist import at the beginning of your project and refferenced for me i just referenceed it as np.

# Simple random data

In [2]:
np.random.rand(4,3)

array([[0.48351363, 0.98546786, 0.80167526],
       [0.59369983, 0.6190609 , 0.9657423 ],
       [0.36194559, 0.96614187, 0.27787631],
       [0.12649085, 0.71219329, 0.8731368 ]])

In [3]:
np.random.rand(3,3)

array([[0.94138325, 0.09618425, 0.58526649],
       [0.02289293, 0.92525154, 0.06451434],
       [0.26130669, 0.31348492, 0.60430664]])

In [4]:
np.random.rand(2,3)

array([[0.248292  , 0.01531071, 0.78989383],
       [0.64155466, 0.54592745, 0.59031813]])

This function allows you to randomly generate an array of numbers in matrix array format

## numpy.random.randint

In [5]:
np.random.randint(2, size=10)

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [6]:
np.random.randint(4, size=10)

array([0, 3, 3, 0, 3, 2, 2, 2, 0, 3])

In [7]:
np.random.randint(-2, size=10)

ValueError: low >= high

In [8]:
np.random.randint(5, size=8)

array([1, 1, 2, 4, 0, 0, 3, 0])

in this funtion numpy.random.randint it prints out a random number between 0 and what ever number you enter, and prints it out in the size of the array you have entered aswel. if you enter a minus it will trough an error as showing.

In [9]:
np.random.randint(5, size=(2, 4))

array([[4, 0, 4, 4],
       [0, 0, 1, 2]])

In [10]:
np.random.randint(6, size=(3, 5))

array([[0, 2, 2, 4, 0],
       [0, 3, 2, 4, 1],
       [1, 2, 4, 4, 1]])

In [11]:
np.random.randint(6, size=(5, 5))

array([[4, 2, 2, 3, 1],
       [2, 3, 2, 0, 4],
       [0, 2, 1, 3, 3],
       [4, 2, 0, 5, 4],
       [3, 4, 2, 4, 5]])

also in this funtion numpy.random.randint generates random numbers in the size of a matrix you wish to enter. 